// <auto-generated/>
global using global::Catcher.Service.AccountService;
global using global::Catcher.Web.Models;
global using global::Microsoft.AspNetCore.Authorization;
global using global::Microsoft.AspNetCore.Builder;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Mvc;
global using global::Microsoft.AspNetCore.Routing;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.Extensions.Logging;
global using global::System.ComponentModel.DataAnnotations;
global using global::Catcher.Model.Entities;
global using global::Microsoft.EntityFrameworkCore;